apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: default  # Adicionado
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /mnt/nfs/postgres-data
    server: 172.31.61.252
