apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default  # Adicionado
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgresuser
        - name: POSTGRES_PASSWORD
          value: postgrespass
        - name: POSTGRES_DB
          value: postgresdb
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
      namespace: default  # Adicionado
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: nfs
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default  # Adicionado
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
